### ISSUE TITLE
is tcltk necessary? can I run in non-interactive mode?

### ISSUE THREAD

**Issue by xmzhuo** [Roth-Lab/pyclone#23]
Traceback (most recent call last):
  File "/opt/conda/bin/PyClone", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python2.7/site-packages/pyclone/cli.py", line 78, in main
    args.func(args)
  File "/opt/conda/lib/python2.7/site-packages/pyclone/run.py", line 97, in run_analysis_pipeline
    args.thin
  File "/opt/conda/lib/python2.7/site-packages/pyclone/run.py", line 409, in _cluster_plot
    samples=samples,
  File "/opt/conda/lib/python2.7/site-packages/pyclone/post_process/plot/clusters.py", line 58, in density_plot
    fig = pp.figure(figsize=(width, height))
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/opt/conda/lib/python2.7/lib-tk/Tkinter.py", line 1825, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

environment: 
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                1.0.1                    py27_0  
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports_abc             0.5                        py_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
cffi                      1.12.3           py27h2e261b9_0  
chardet                   3.0.4                 py27_1003  
conda                     4.8.3            py27h8c360ce_1    conda-forge
conda-package-handling    1.6.0            py27h7b6447c_0  
cryptography              2.7              py27h1ba5d50_0  
cycler                    0.10.0                     py_2    conda-forge
enum34                    1.1.6                    py27_1  
freetype                  2.10.4               h7ca028e_0    conda-forge
funcsigs                  1.0.2                      py_3    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
futures                   3.3.0                    py27_0  
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                      py27_0  
ipaddress                 1.0.22                   py27_0  
kiwisolver                1.1.0            py27h9e3301b_1    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.5.0               h14aa051_18    conda-forge
libgfortran4              7.5.0               h14aa051_18    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.31.0           py27h5ee40b5_1    conda-forge
matplotlib-base           2.2.5            py27h250f245_1    conda-forge
ncurses                   6.1                  he6710b0_1  
numba                     0.47.0           py27hb3f55d8_0    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pandas                    0.24.2           py27hb3f55d8_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pip                       19.2.3                   py27_0  
pyclone                   0.13.1                     py_0    bioconda
pycosat                   0.6.3            py27h14c3975_0  
pycparser                 2.19                     py27_0  
pydp                      0.2.4                      py_0    bioconda
pyopenssl                 19.0.0                   py27_0  
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1                    py27_0  
python                    2.7.16               h9bab390_7  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.1.2            py27h516909a_0    conda-forge
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py27_0  
ruamel_yaml               0.15.46          py27h14c3975_0  
scipy                     1.2.1            py27h921218d_2    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
setuptools                41.4.0                   py27_0  
singledispatch            3.6.1              pyh44b312d_0    conda-forge
six                       1.12.0                   py27_0  
sqlite                    3.30.0               h7b6447c_0  
statsmodels               0.10.2           py27hc1659b7_0    conda-forge
subprocess32              3.5.4            py27h516909a_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tornado                   5.1.1           py27h14c3975_1000    conda-forge
tqdm                      4.36.1                     py_0  
urllib3                   1.24.2                   py27_0  
wheel                     0.33.6                   py27_0  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3

**Comment by xmzhuo** [comment]
update:

work after set matplotlib in agg mode
sed -i 's/\(backend *: \).*$/\1Agg/g' $( python -c "import matplotlib; print(matplotlib.matplotlib_fname())" )

**Comment by aroth85** [comment]
Sorry I missed this. This and several other issues have been answered on the user group for future reference https://groups.google.com/g/pyclone-user-group. Really need an FAQ page at some point.
